version: '3.8'

services:
  database-mc:
    image: postgres:latest
    environment:
      POSTGRES_DB: communicationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - postgres-data-user:/var/lib/postgresql/data
    networks:
      - demo_net

  application-mc:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - database-mc
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-mc:5432/communicationdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - demo_net

networks:
  demo_net:
    external:
      name: demo_net

volumes:
  postgres-data-user:
