version: '3.8'

services:
  database-userservice:
    image: postgres:latest
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres-data-user:/var/lib/postgresql/data
    networks:
      - demo_net

  application-userservice:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - database-userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-userservice:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - demo_net

networks:
  demo_net:
    external:
      name: demo_net

volumes:
  postgres-data-user:
